---
title: "FinalProject_Proposal"
output: html_document
---
##Project Background  
Colletotrichum species have become economically devastating pathogens of chestnut (Castanea spp) crops in Ohio in within the last decade. The disease cycle is unknown. Based on what we know of the Colletotrichum disease cycle in apple (Malus spp), we hypothesize that weather conditions at bloom and harvest times are correlated with disease incidence, and that warmer, wetter conditions which favor spore dispersal and fungal growth are correlated with higher disease incidence. We will use data from a weather station at Empire Chestnut Company in Carrollton, OH and look for correlations between those data and disease incidence in chestnut at harvest in 2020-2021. 

##Project Description  
The goal of this project is to sort and organize the weather data into formats that can be used for downstream data analysis. The raw files are too large to be manipulated with a GUI spreadsheet program such as Excel. 

###Weather Data To Do:  
* Because the weather station was renamed three times, columns are redundant and need to be combined so that each weather parameter is one column instead of 3
+ Export each parameter into its own file, and then combine columns? 
+ Combine the files so that each parameter appears as a single column in 1 file?
+ Make this a script so that it can all be run at once with a single output file (csv)
*Choose one parameter to write code, make that code generic so that it can be applied to any other parameter
+ Start with Air Temperature, test the code
+ Make a minor adjustment (rename a variable) so that it works with Rainfall

###Flow of code for each weather parameter:  
* Pull out rows corresponding to date range of interest (i.e. one month)
* Pull out rows corresponding to each day
* Determine an average value for the rows corresponding to each day
* Determine a minimum and maximum value for the rows corresponding to each day
* Write this as script so it can be automated for each day of the target date range
* Create an output file (csv) with rows correspoding to each date and columns for average, min, and max values


##Technical Details:  
Coding language = R (RStudio Server available through OSC)  
Version Control via Git integrated into RStudio  
Use Bash to run scripts (mentioned above)  
I will not do this as a SLURM job through OSC because it's unnecessary given the small size of the data file, as we discussed
I will try to make this re-runnable as a Snakefile, but not sure how to do that since we haven't covered it in class
